/**
 * @file soft_i2c_master.h
 * @brief Static software-I2C transaction engine built on line capabilities.
 * @author Codex
 * @date 2026-09-18
 * @note This is a synchronous master. The delay token, delay duration and
 * maximum clock-high polls are compile-time policy; no runtime bus object or
 * function table is retained. The transfer address is a 7-bit address.
 */
#ifndef MDI_FEATURE_SOFT_I2C_MASTER_H
#define MDI_FEATURE_SOFT_I2C_MASTER_H
#include "mdi/feature/soft_i2c_edges.h"

/** @brief Bind a bounded software-I2C master to a line policy.
 * @param NAME Resource token generated by this binding.
 * @param BUS Previously bound software-I2C edge resource.
 * @param DELAY Zero-argument delay function or macro, already calibrated.
 * @param DELAY_US Duration of one DELAY call, used to derive timeout polls.
 * @param MAX_WAIT Maximum delay calls while waiting for SCL to be high.
 * @return Generates the MDI_I2C_Transfer provider.
 * @note The caller owns bus serialization and must configure both pins as
 * open-drain with pull-ups. A transfer timeout is rounded up to delay calls
 * and capped by MAX_WAIT.
 */
#define MDI_SOFT_I2C_MASTER_BIND(NAME, BUS, DELAY, DELAY_US, MAX_WAIT)           \
    _Static_assert((DELAY_US) > 0U, "I2C delay duration must be nonzero");       \
    _Static_assert((MAX_WAIT) > 0U, "I2C clock wait bound must be nonzero");     \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_WaitClock)(                        \
        uint32_t wTimeoutUs)                                                     \
    {                                                                            \
        uint32_t wPoll;                                                          \
        uint32_t wPolls = (wTimeoutUs + (DELAY_US) - 1U) / (DELAY_US);           \
        if (wPolls == 0U) { wPolls = 1U; }                                       \
        if (wPolls > (MAX_WAIT)) { wPolls = (MAX_WAIT); }                        \
        for (wPoll = 0U; wPoll < wPolls; ++wPoll) {                              \
            if (MDI_SoftI2C_ReadScl(BUS)) { return MDI_OK; }                     \
            DELAY();                                                             \
        }                                                                        \
        return MDI_TIMEOUT;                                                      \
    }                                                                            \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_Start)(                            \
        uint32_t wTimeoutUs)                                                     \
    {                                                                            \
        mdi_status_t eStatus;                                                    \
        MDI_SoftI2C_SdaRelease(BUS);                                             \
        DELAY();                                                                 \
        MDI_SoftI2C_SclRelease(BUS);                                             \
        eStatus = MDI_OP(NAME, _i2c_WaitClock)(wTimeoutUs);                      \
        if (eStatus != MDI_OK) { return eStatus; }                               \
        MDI_SoftI2C_SdaLow(BUS);                                                 \
        DELAY();                                                                 \
        MDI_SoftI2C_SclLow(BUS);                                                 \
        DELAY();                                                                 \
        return MDI_OK;                                                           \
    }                                                                            \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_Stop)(                             \
        uint32_t wTimeoutUs)                                                     \
    {                                                                            \
        mdi_status_t eStatus;                                                    \
        MDI_SoftI2C_SdaLow(BUS);                                                 \
        MDI_SoftI2C_SclLow(BUS);                                                 \
        DELAY();                                                                 \
        MDI_SoftI2C_SclRelease(BUS);                                             \
        eStatus = MDI_OP(NAME, _i2c_WaitClock)(wTimeoutUs);                      \
        if (eStatus != MDI_OK) { return eStatus; }                               \
        MDI_SoftI2C_SdaRelease(BUS);                                             \
        DELAY();                                                                 \
        return MDI_OK;                                                           \
    }                                                                            \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_WriteBitByte)(                     \
        uint8_t chValue, uint32_t wTimeoutUs)                                    \
    {                                                                            \
        uint8_t chBit;                                                           \
        mdi_status_t eStatus;                                                    \
        for (chBit = 0U; chBit < 8U; ++chBit) {                                  \
            MDI_SoftI2C_SclLow(BUS);                                             \
            if ((chValue & 0x80U) != 0U) {                                       \
                MDI_SoftI2C_SdaRelease(BUS);                                     \
            } else {                                                             \
                MDI_SoftI2C_SdaLow(BUS);                                         \
            }                                                                    \
            DELAY();                                                             \
            MDI_SoftI2C_SclRelease(BUS);                                         \
            eStatus = MDI_OP(NAME, _i2c_WaitClock)(wTimeoutUs);                  \
            if (eStatus != MDI_OK) { return eStatus; }                           \
            DELAY();                                                             \
            chValue = (uint8_t)(chValue << 1U);                                  \
        }                                                                        \
        MDI_SoftI2C_SclLow(BUS);                                                 \
        MDI_SoftI2C_SdaRelease(BUS);                                             \
        DELAY();                                                                 \
        MDI_SoftI2C_SclRelease(BUS);                                             \
        eStatus = MDI_OP(NAME, _i2c_WaitClock)(wTimeoutUs);                      \
        if (eStatus != MDI_OK) { return eStatus; }                               \
        if (MDI_SoftI2C_ReadSda(BUS)) {                                          \
            eStatus = MDI_IO_ERROR;                                              \
        } else {                                                                 \
            eStatus = MDI_OK;                                                    \
        }                                                                        \
        MDI_SoftI2C_SclLow(BUS);                                                 \
        DELAY();                                                                 \
        return eStatus;                                                          \
    }                                                                            \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_ReadByte)(                         \
        uint8_t *pchValue, uint32_t wTimeoutUs)                                  \
    {                                                                            \
        uint8_t chBit;                                                           \
        uint8_t chValue = 0U;                                                    \
        mdi_status_t eStatus;                                                    \
        if (pchValue == NULL) { return MDI_INVALID; }                            \
        MDI_SoftI2C_SdaRelease(BUS);                                             \
        for (chBit = 0U; chBit < 8U; ++chBit) {                                  \
            MDI_SoftI2C_SclRelease(BUS);                                         \
            eStatus = MDI_OP(NAME, _i2c_WaitClock)(wTimeoutUs);                  \
            if (eStatus != MDI_OK) { return eStatus; }                           \
            DELAY();                                                             \
            chValue = (uint8_t)(chValue << 1U);                                  \
            if (MDI_SoftI2C_ReadSda(BUS)) { chValue = (uint8_t)(chValue | 1U); } \
            MDI_SoftI2C_SclLow(BUS);                                             \
            DELAY();                                                             \
        }                                                                        \
        *pchValue = chValue;                                                     \
        return MDI_OK;                                                           \
    }                                                                            \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_Ack)(                              \
        bool bAck, uint32_t wTimeoutUs)                                          \
    {                                                                            \
        mdi_status_t eStatus;                                                    \
        if (bAck) { MDI_SoftI2C_SdaLow(BUS); }                                   \
        else { MDI_SoftI2C_SdaRelease(BUS); }                                    \
        DELAY();                                                                 \
        MDI_SoftI2C_SclRelease(BUS);                                             \
        eStatus = MDI_OP(NAME, _i2c_WaitClock)(wTimeoutUs);                      \
        MDI_SoftI2C_SclLow(BUS);                                                 \
        DELAY();                                                                 \
        return eStatus;                                                          \
    }                                                                            \
    MDI_INLINE mdi_status_t MDI_OP(NAME, _i2c_Transfer)(                         \
        const mdi_i2c_transfer_t *ptTransfer)                                    \
    {                                                                            \
        mdi_status_t eStatus;                                                    \
        uint32_t wIndex;                                                         \
        if (ptTransfer == NULL) { return MDI_INVALID; }                          \
        if (ptTransfer->hwAddress7 > 0x7FU) { return MDI_RANGE; }                \
        if (ptTransfer->wTimeoutUs == 0U) { return MDI_TIMEOUT; }                \
        if ((ptTransfer->wTxLength == 0U) && (ptTransfer->wRxLength == 0U)) {    \
            return MDI_INVALID;                                                  \
        }                                                                        \
        if (((ptTransfer->wTxLength != 0U) && (ptTransfer->pchTx == NULL)) ||    \
            ((ptTransfer->wRxLength != 0U) && (ptTransfer->pchRx == NULL))) {    \
            return MDI_INVALID;                                                  \
        }                                                                        \
        eStatus = MDI_OP(NAME, _i2c_Start)(ptTransfer->wTimeoutUs);              \
        if (eStatus != MDI_OK) { return eStatus; }                               \
        if (ptTransfer->wTxLength != 0U) {                                       \
            eStatus = MDI_OP(NAME, _i2c_WriteBitByte)(                           \
                (uint8_t)(ptTransfer->hwAddress7 << 1U),                         \
                ptTransfer->wTimeoutUs);                                         \
            if (eStatus == MDI_OK) {                                             \
                for (wIndex = 0U; wIndex < ptTransfer->wTxLength; ++wIndex) {    \
                    eStatus = MDI_OP(NAME, _i2c_WriteBitByte)(                   \
                        ptTransfer->pchTx[wIndex], ptTransfer->wTimeoutUs);      \
                    if (eStatus != MDI_OK) { break; }                            \
                }                                                                \
            }                                                                    \
        }                                                                        \
        if ((eStatus == MDI_OK) && (ptTransfer->wRxLength != 0U)) {              \
            if (ptTransfer->wTxLength != 0U) {                                   \
                eStatus = MDI_OP(NAME, _i2c_Start)(                              \
                    ptTransfer->wTimeoutUs);                                     \
            }                                                                    \
            if (eStatus == MDI_OK) {                                             \
                eStatus = MDI_OP(NAME, _i2c_WriteBitByte)(                       \
                    (uint8_t)((ptTransfer->hwAddress7 << 1U) | 1U),              \
                    ptTransfer->wTimeoutUs);                                     \
            }                                                                    \
            for (wIndex = 0U; (eStatus == MDI_OK) &&                             \
                 (wIndex < ptTransfer->wRxLength); ++wIndex) {                   \
                eStatus = MDI_OP(NAME, _i2c_ReadByte)(                           \
                    &ptTransfer->pchRx[wIndex], ptTransfer->wTimeoutUs);         \
                if (eStatus == MDI_OK) {                                         \
                    eStatus = MDI_OP(NAME, _i2c_Ack)(                            \
                        (wIndex + 1U) < ptTransfer->wRxLength,                   \
                        ptTransfer->wTimeoutUs);                                 \
                }                                                                \
            }                                                                    \
        }                                                                        \
        if (eStatus != MDI_OK) {                                                 \
            (void)MDI_OP(NAME, _i2c_Stop)(ptTransfer->wTimeoutUs);               \
            return eStatus;                                                      \
        }                                                                        \
        return MDI_OP(NAME, _i2c_Stop)(ptTransfer->wTimeoutUs);                  \
    }
#endif
